### ISSUE TITLE
Question about : etcd documentation

### ISSUE THREAD

**Issue by robinportigliatti** [mvallim/kubernetes-under-the-hood#129]
Hello,

I am learning about etcd and TLS and found your repo but I am stuck. Found a solution using `cfssl` but I want to use `openssl` directly. Nor `peer` or `server` extensions are available and I can't find the `config.conf` file you are using.

Could you share it or point me where I can find it ?

Robin,

**Comment by mvallim** [comment]
Hi @robinportigliatti,

Did you take a look at this thread?

This topic explains step by step how to generate the certificate and the configuration files for each of the parts (root, ca, server, peer and user)

https://github.com/mvallim/kubernetes-under-the-hood/blob/master/documentation/ca-external-infrastructure.md#creating-the-certificates

And here explain how to generate certificates to etcd.

https://github.com/mvallim/kubernetes-under-the-hood/blob/master/documentation/etcd.md#creating-certificates

Best regards,

**Comment by robinportigliatti** [comment]
Hi @mvallim,

Thank you. I managed to do a little script implementing openssl ca tuorial and your documentation https://github.com/robinportigliatti/openssl-tryon

Robin,
