### ISSUE TITLE
Unable to access Demo Application Website from Host Computer

### ISSUE THREAD

**Issue by CallumQuin** [mvallim/kubernetes-under-the-hood#75]
Hi Team,

I have been working my way through your Kubernetes under the hood project in order to deploy a small production Kubernetes server at work for use by our development team.

I have been able to deploy and setup all of the masters/nodes using your instructions as well as launch the demo application. However I am running into an issue with accessing the website service once deployed. The project says to go to http://kube-node01.kube.demo:{NodePort} however when i try to do this I get a server not found error.

Also when i try to nslookup kube-node01 from the host computer I am unable to find the ip address assigned so think potentially I am missing a  IP route on the host to get to the DNS/node network? When ssh'd into the busybox I am able to nslookup kube-node01 succesfully and also curl the website and get the correct response.

Any help on trying to work out what is going wrong here would be much appreciated. I believe I have followed all the documentation correctly to this stage but may have missed something.

Thanks for you help,
Callum

**Comment by mvallim** [comment]
Hi @CallumQuin,

Sorry for my late!

I updated the documentation, you will check [here](https://github.com/mvallim/kubernetes-under-the-hood/blob/master/documentation/kube-demo-application.md#demo-application)

If you have any problems, let me know.

Thank you for your contribution.
